# Generated by Django 5.2.1 on 2025-05-24 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relatos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='relato',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relatos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Autor',
        ),
    ]
